# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(808, 432)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.songLibrary = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.songLibrary.setObjectName("songLibrary")
        self.verticalLayout.addWidget(self.songLibrary)
        self.playListList = QtWidgets.QListView(self.verticalLayoutWidget)
        self.playListList.setObjectName("playListList")
        self.verticalLayout.addWidget(self.playListList)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(420, 330, 361, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.playbackButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playbackButton.setObjectName("playbackButton")
        self.horizontalLayout.addWidget(self.playbackButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(420, 280, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeLable = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.timeLable.setObjectName("timeLable")
        self.horizontalLayout_2.addWidget(self.timeLable)
        self.timeSlider = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_2.addWidget(self.timeSlider)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 230, 361))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.clearPlayListButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clearPlayListButton.setObjectName("clearPlayListButton")
        self.horizontalLayout_5.addWidget(self.clearPlayListButton)
        self.savePlayListButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.savePlayListButton.setObjectName("savePlayListButton")
        self.horizontalLayout_5.addWidget(self.savePlayListButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.currentPlayList = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.currentPlayList.setObjectName("currentPlayList")
        self.verticalLayout_3.addWidget(self.currentPlayList)
        Ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName("menubar")
        Ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle(_translate("Ui_MainWindow", "MainWindow"))
        self.previousButton.setText(_translate("Ui_MainWindow", "<<"))
        self.playbackButton.setText(_translate("Ui_MainWindow", "Play/Pause"))
        self.nextButton.setText(_translate("Ui_MainWindow", ">>"))
        self.timeLable.setText(_translate("Ui_MainWindow", "0:0/0:0"))
        self.clearPlayListButton.setText(_translate("Ui_MainWindow", "Clear"))
        self.savePlayListButton.setText(_translate("Ui_MainWindow", "Save as playlist"))
